name: Scout Mayotte Education
on:
  workflow_dispatch:

jobs:
  scout:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run scout
        run: python3 scout.py
